// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "509ardakereact-20191108155308-hostingbucket-react",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://509ardakereact-20191108155308-hostingbucket-react.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
